---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2022-02-16T03:25:30.616002995Z"
  name: result
  namespace: instavote
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@exmaple.com
        name: flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: instavote
  update:
    path: ./helm/charts/result
    strategy: Setters

