---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: result
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/charts/result
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: instavote
      version: '*'
  interval: 10m0s
  targetNamespace: instavote

