apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- canary.yaml
- deployment.yaml
namespace: instavote
images:
- name: dockeridjz/vote
  newTag: main-59050f61-1645018960 # {"$imagepolicy": "instavote:vote:tag"}
replicas:
- name: vote
  count: 0
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
